version: '3'
services:
  api:
    image: flashcards-api:local
    volumes:
      - ./docker/conf/api:/conf
    depends_on:
      postgres:
        condition: service_healthy
    command: [ "-Dlogback.configurationFile=/conf/logback.xml",
               "-Dconfig.file=/conf/application.conf",
               "-Dcom.sun.management.jmxremote=true",
               "-Dcom.sun.management.jmxremote.local.only=false",
               "-Dcom.sun.management.jmxremote.authenticate=false",
               "-Dcom.sun.management.jmxremote.ssl=false",
               "-Djava.rmi.server.hostname=localhost",
               "-Dcom.sun.management.jmxremote.port=9010",
               "-Dcom.sun.management.jmxremote.rmi.port=9010" ]
    healthcheck:
      test: [curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 1s
      retries: 5

  migrations:
    image: flyway/flyway:9-alpine
    command: ["-url=jdbc:postgresql://postgres:5432/flashcards",
              "-schemas=public",
              "-user=postgres",
              "-password=postgres",
              "-connectRetries=5",
              "migrate"]
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./docker/migrations/:/flyway/sql

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flashcards
      - PGUSER=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 5s
      timeout: 1s
      retries: 5
